# Generated by Django 3.2.9 on 2021-11-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_auto_20211124_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='descricao',
            field=models.TextField(default='Descricao'),
            preserve_default=False,
        ),
    ]
